# Site settings
author: Matthew T. Ream
title: Matthew Ream
header-img: img/home-bg.png
email: matthewtimothyream@gmail.com
copyright_name: Matthew T. Ream
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mattream15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
